apiVersion: v2
appVersion: v1.12.1
description: homepage helm chart for Kubernetes
home: https://github.com/gethomepage/homepage
icon: https://artifacthub.io/image/e417b561-5fe4-4ee3-9b89-f67df4069169
kubeVersion: '>=1.23.0-0'
maintainers:
  - email: ludovic.ortega@adminafk.fr
    name: Ludovic Ortega
name: homepage
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/homepage
type: application
version: 4.10.1
