apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: torre-ns
  labels:
    app.kubernetes.io/name: homepage
data:
  HOMEPAGE_ALLOWED_HOSTS: "homepage.dyn.cloud.e-infra.cz,gethomepage.dev,127.0.0.1,localhost"
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    theme: dark
  custom.css: |
    body {
    background-color: #ffffff;
    color: #005FAA;
    font-family: "Open Sans", Arial, sans-serif;
    }
    button, .btn {
    background-color: #EF8200 !important;
    color: #ffffff !important;
    border-radius: 6px;
    font-weight: bold;
    }
    button:hover, .btn:hover, .btn-primary:hover {
    background-color: #FF9C4D !important;
    color: #ffffff !important;
    }
    header {
    background: #ffffff;
    border-bottom: 3px solid #EF8200;
    }
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/EGI-Federation
    - Website:
        - EGI Foundation:
            - abbr: EGI
              href: https://www.egi.eu/
    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://www.youtube.com/@EGI_eInfra
  services.yaml: |
    - Compute & Cloud Orchestration:
        - Rancher:
            icon: rancher.png
            href: https://rancher.cloud.e-infra.cz/dashboard/
            description: EGI Container Compute, manage and orchestrate distributed applications on EGI cloud clusters.
        - Infrastructure Manager:
            icon: https://www.google.com/s2/favicons?domain=im.egi.eu&sz=32
            href: https://im.egi.eu/
            description: EGI Cloud orchestrator to deploy and configure complex virtual infrastructures.
        - OpenStack Provider Dashboards:
            icon: openstack.png
            href: https://dashboard.cloud.egi.eu/
            description: Access to the OpenStack dashboards of the EGI FedCloud providers.
        - Dynamic DNS:
            icon: https://www.google.com/s2/favicons?domain=fedcloud.eu&sz=32
            href: https://nsupdate.fedcloud.eu/
            description: EGI Dynamic DNS service to update and manage DNS records for cloud resources.

    - Applications & Platforms (SaaS):
        - EGI Notebooks:
            icon: jupyter.png
            href: https://notebooks.egi.eu/
            description: Interactive Jupyter environment for scientific data analysis, visualization and collaborative sharing.
        - EGI Replay:
            icon: https://www.google.com/s2/favicons?domain=mybinder.org&sz=32
            href: https://replay.notebooks.egi.eu/
            description: Create interactive documents with live code, visualisations and text.
        - EGI Workload Manager:
            icon: https://www.google.com/s2/favicons?domain=dirac.egi.eu&sz=32
            href: https://dirac.egi.eu/
            description: EGI Workload Manager for managing and scheduling workloads across EGI resources.

    - Data & Storage Services:
        - DataHub:
            icon: https://www.google.com/s2/favicons?domain=datahub.egi.eu&sz=32
            href: https://datahub.egi.eu/ozw/onezone/i#/login
            description: EGI DataHub - OneData. Distributed data platform to share, replicate and access scientific datasets across European infrastructures.
        - Vault:
            icon: vault.png
            href: https://vault.services.fedcloud.eu:8200/ui/vault/auth?with=userpass
            description: EGI Secret store manager, protect and store user secrets, credentials and sensitive information.
        - Harbor:
            icon: harbor.png
            href: https://registry.egi.eu/
            description: EGI Artefact Registry, store, share and distribute containers and software packages securely.

    - Identity & VO Management:
        - Keycloak:
            icon: keycloak.png
            href: https://aai.egi.eu/
            description: EGI Authentication & Authorization Infrastructure providing secure federated access to EGI services.
        - Operations Portal:
            icon: https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/EGI_Logo.svg/999px-EGI_Logo.svg.png
            href: https://operations-portal.egi.eu/
            description: VO management platform for VO administration, broadcasts, downtimes, dashboards, metrics, SLA tracking, and VO lists.
        - Your Virtual Organization:
            icon: https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/EGI_Logo.svg/999px-EGI_Logo.svg.png
            href: https://dashboard.appdb.egi.eu/vmops
            description: Legacy, should we remove ? Personal dashboard to manage user’s Virtual Organizations and related resources across the infrastructure.

    - Monitoring & Accounting:
        - EGI ARGO Monitoring:
            #icon: https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/EGI_Logo.svg/999px-EGI_Logo.svg.png
            icon: https://www.google.com/s2/favicons?domain=argoeu.github.io&sz=32
            href: https://argo.egi.eu/
            description: Service to monitor availability, reliability and operational status of EGI sites and services.
        - EGI Accounting Portal:
            icon: https://cdn.egi.eu/app/uploads/2022/06/egi-icon-high-throughput-compute.png
            #icon: https://www.google.com/s2/favicons?domain=accounting.egi.eu&sz=32
            href: https://accounting.egi.eu/
            description: Portal to explore, filter and analyze resource usage across the EGI infrastructure.
        - GOCDB:
            icon: https://www.google.com/s2/favicons?domain=goc.egi.eu&sz=32
            href: https://goc.egi.eu/
            description: Configuration database collecting and managing service and site information for the EGI federation.
        # - Grafana:
        #     icon: grafana.png
        #     href: https://grafana.egi.eu/
        #     description: EGI Grafana instance
        # - Prometheus:
        #     icon: prometheus.png
        #     href: https://prometheus.egi.eu/
        #     description: EGI Prometheus instance

    - Support & Documentation:
        - EGI Helpdesk:
            icon: https://www.google.com/s2/favicons?domain=helpdesk.ggus.eu&sz=32
            href: https://helpdesk.ggus.eu/
            description: Centralized support service for technical requests, incident reports and user assistance tickets.
        - Documentation:
            icon: https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/EGI_Logo.svg/999px-EGI_Logo.svg.png
            href: https://docs.egi.eu/
            description: Knowledge portal with guides, tutorials and manuals for EGI users and service providers.
        - EGI FedCloud Slack Channel:
            icon: slack.png
            href: https://egifedcloud.slack.com
            description: Community channel for announcements, discussions and collaborative support among EGI users.

  settings.yaml: |

    providers:
      openweathermap: openweathermapapikey
      weatherapi: weatherapiapikey
    title: "EGI Cloud Dashboard"
    background:
      image: https://www.egi.eu/_next/image/?url=https%3A%2F%2Fcdn.egi.eu%2Fapp%2Fuploads%2F2022%2F05%2Fweb-images-38.png&w=3840&q=75 
      blur: x8
      saturate: 20
      brightness: 255
      opacity: 5
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""